### ISSUE TITLE
Is there a tutorial on how to use it

### ISSUE THREAD

**Issue by chenxyzl** [thesayyn/protoc-gen-ts#1]
I want to trying，but no tutorials found in readme。
thanks

**Comment by thesayyn** [comment]
I haven't published the package yet. This weekend I will push some fixes and publish a npm package.  
For now, you can clone the project and run `yarn examples` command to generate your proto files.

**Comment by chenxyzl** [comment]
Looking forward to your release，thank

**Comment by thesayyn** [comment]
@chenxyzl I have provided an example.
