### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by seishun** [thesayyn/protoc-gen-ts#10]
There should be a LICENSE file in the project with license information so people know if they can use it in their own projects.

**Comment by thesayyn** [comment]
Yes we should add an license file however if if take look at published packages on npm, you'll see that it is published under MIT license.

**Comment by seishun** [comment]
The MIT license has the following line:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

I can't meet this condition without a license file.

**Comment by thesayyn** [comment]
Closed in 0.0.6 release. Thank you for the report.
