### ISSUE TITLE
Option for making all properties required except optional fields

### ISSUE THREAD

**Issue by erikljung** [thesayyn/protoc-gen-ts#119]
This is probably wrong, but just to learn something. I would expect that a message like:
`
message SomeThing {
  string Foo = 1;
  optional Bar = 1;
}
`
should give a class with a constructor like:
`
{
  foo: string;
  bar?: string;
}
`
This is apparently not the case. Could someone elaborate on why this is, and would it be possible to make this an ts_opt?

**Comment by thesayyn** [comment]
that should be the case.  see: https://github.com/thesayyn/protoc-gen-ts/blob/main/test/_/optional  and generated code https://github.com/thesayyn/protoc-gen-ts/tree/main/test/optional

**Comment by thesayyn** [comment]
see #120 for more cases. this PR has to behavior changes present.

**Comment by erikljung** [comment]
I'm not sure I follow. What does not work for me is that fields that are **not** `optional` still get rendered as `?`, it seems to me like everything gets rendered as `optional`. I use _compiler version: 3.19.3_ it seems to be _3.17.0_ in the code you sent.

**Comment by erikljung** [comment]
```
message AddItemErrorMessage {
   string some_id = 1;
   string error_message = 2;
   int32 units_available = 3;
   int32 units_requested = 4;
}
```
gives:
```
 export class AddItemErrorMessage extends pb_1.Message {
        constructor(data?: any[] | {
            some_id?: string;
            error_message?: string;
            units_available?: number;
            units_requested?: number;
        }) ...
```

**Comment by thesayyn** [comment]
> I'm not sure I follow.

sorry, there was a typo in my statement. 

> What does not work for me is that fields that are **not** `optional` still get rendered as `?`, it seems to me like everything gets rendered as `optional`

by default, all fields are optional in proto3. if you switch to proto2, you will the that the optional keyword reflects your proto files.

**Comment by erikljung** [comment]
Yes, I guess you're right. It's probably just me that wants the wrong thing :).. Thanks for your help.

**Comment by thesayyn** [comment]
glad to help.

**Comment by thesayyn** [comment]
Feel free to reopen if you have further questions.
