### ISSUE TITLE
bigint support

### ISSUE THREAD

**Issue by muddle216** [thesayyn/protoc-gen-ts#122]
Can I get "bigint" member for TYPE_UINT64 instead of "number"? Thanks!

**Comment by thesayyn** [comment]
you are welcome to send a PR if you could make it work google-protobuf which I don't think is possible without google-protobuf support first.

See: https://github.com/protocolbuffers/protobuf/issues/7244

**Comment by thesayyn** [comment]
I have made a small experiment to find out if we could make this work without changing `google-protobuf`. answer is yes!
`readUint64String` and `readInt64String` is your friend here.

**Comment by muddle216** [comment]
Thank you for your help! I am trying to add an option "int64_to_string" which changing the return of "hasJsTypeString". But my work is not finished. And I have no experience to send a PR.
Will you please commit your code, and update release version?

**Comment by thesayyn** [comment]
I just experimented with a generated code. I didn't change the generator to produce bigint output. i just confirmed that it would work with `readUint64String` and `readInt64String`

**Comment by thesayyn** [comment]
Unfortunately, I don't have the time to implement this for you.

**Comment by muddle216** [comment]
OK, thank you all the same! I want to test my code, but I don't know how to call my code through "protoc --ts_out". Is there any WIKI or document that is about to debug protoc?

**Comment by chris-kruining** [comment]
@muddle216 the plugin system works quite nice I must say, your code just gets called as any program would. On the STDIN is your Request, and on the STD out your Response, these 2 messages are just grpc, which means you compile grpc using grpc. 

to go into some more detail, protoc with it's plugins is simple/dumb if you have a pattern of `--{something}_out` as a parameter on your protoc call, protoc will look for a `protoc-gen-{something}` on your `PATH`. in this case we are using ts, so `--ts_out` get turned into `protoc-gen-ts`. Where `protoc-gen-ts` is a executable on your `PATH`

**Comment by furstenheim-goodnotes** [comment]
Hi @muddle216 , could you share what you did? I'm also interested in using bigint for int64. Thanks!

**Comment by thesayyn** [comment]
This is fixed with the rust rewrite. Now we support bigints

**Comment by muddle216** [comment]
> Hi @muddle216 , could you share what you did? I'm also interested in using bigint for int64. Thanks!

Sorry, I didn't finish the work.

**Comment by muddle216** [comment]
> This is fixed with the rust rewrite. Now we support bigints

Thank you very much! But I can't find the rust project address. Can you provide me with the project link, please?

**Comment by thesayyn** [comment]
> > This is fixed with the rust rewrite. Now we support bigints
> 
> Thank you very much! But I can't find the rust project address. Can you provide me with the project link, please?

Checkout the main branch. Its now in rust

**Comment by erba** [comment]
@thesayyn What does it mean that it is now in rust?
I guess we will need to await the next release for the bigint support...?
Great work with this plugin btw!

**Comment by thesayyn** [comment]
I rewrote the plugin in Rust and made a lot of changes, one of which includes bigint support.  You can clone the repo and run `./infra/compile.sh` to get an npm package to test out.

**Comment by thesayyn** [comment]
https://github.com/thesayyn/protoc-gen-ts/pkgs/npm/protoc-gen-ts/150540837 is the unreleased version you can use.
