### ISSUE TITLE
Support strip_import_prefix on proto_library rules

### ISSUE THREAD

**Issue by chris-codaio** [thesayyn/protoc-gen-ts#124]
When using `strip_import_prefix` on a `proto_library` rule, then attempting to consume that proto output via `ts_proto_library`, I get back an error:

```
ERROR: /modules/protos/protos/BUILD:8:14: output 'modules/protos/protos/bazel-out/darwin-fastbuild/bin/_virtual_imports/my_proto/my_service.ts' was not created
ERROR: /modules/protos/protos/BUILD:8:14: Generating Protocol Buffers for Typescript //modules/protos/protos:my_service_proto failed: not all outputs were created or valid
```

**Comment by thesayyn** [comment]
Ah, yes looks like we need special handling for `_virtual_imports` directory. do you mind sending a PR for this? with additional tests?

**Comment by thesayyn** [comment]
Not relevant anymore as we don't have a bazel rule anymore
