### ISSUE TITLE
running after npm ci behaves incorrect while running after npm install is as expected

### ISSUE THREAD

**Issue by relief-melone** [thesayyn/protoc-gen-ts#127]
node version: tested wich 12,14 and 17
prococ-gen-ts version: tested with 0.8.0 and 0.8.1

I currently stumbled over the following issue in one of my pipelines that utilizes npm ci instead of npm install. When running

```sh 
npm install
npm run build
```
output generated is typescript files as expected. However when running

```
npm ci
npm run build
```

only declarations are in the output folder. I generated a simple repo that reproduces the error [here](https://gitlab.com/rm-issues/protoc-gen-ts_npm_ci_fails). I noticed that the protoc-gen-ts files in my node_modules/.bin folder differed based on having been installed via npm install or ci. 

**contents for working script**
```js
#!/usr/bin/env node
require('../src/index')
```

**contents when build failed**
```js
#!/usr/bin/env node

var LibPath = require('path');

require(LibPath.join(__dirname, '../build/index'));
```

Now i do not know if this is the root cause or just a side effect. Would be great if this could be investigated.

**Comment by thesayyn** [comment]
I am not sure I understand the issue here. it is not possible for the plugin to emit only `.d.ts`. there is no such capability. i believe that it has something to do with the way you utilize the tool. perhaps you run `tsc` after `protoc` and typescript deletes the `.ts` files and replaces them with `.d.ts` counterparts?

**Comment by relief-melone** [comment]
I found this behaviour very odd as well and and cannot explain it. Will also tried to investigate. However I can rule out that the typscript compiler deletes the .ts files. you can also run

```
npm run build:protoc
```

which will only run the typescript generation not the tsc. The result will also be .d.ts files instead of .ts. Could this maybe have something to do with the different imports in the bin script?

**Comment by thesayyn** [comment]
As I stated before `protoc-gen-ts` is incapable of outputting `d.ts` files directly. I believe that you have a problem that is specific to your configuration.

Feel free to reopen if you still believe that `protoc-gen-ts` is faulty here.
