### ISSUE TITLE
TypeError when using protoc-gen-ts v0.8.2 with buf v1.4.0

### ISSUE THREAD

**Issue by varungandhi-src** [thesayyn/protoc-gen-ts#139]
Thank you for creating and maintaining this project.

I noticed a bug when using v0.8.2 of this project along with buf v1.4.0. I've created a repository with configuration that should help you reproduce the issue: https://github.com/varungandhi-src/protoc-gen-ts-bug (commit: 628fda220). I've copied the project's README below for convenience.

It seems like a regression that crept in some time between v0.8.1 and v0.8.2.

Unfortunately, I wasn't able to quite figure out how `buf` is invoking this plugin, so I don't have a minimal example without `buf`.

---

Stack trace:

```
/Users/varun/Code/protoc-gen-ts-bug/node_modules/protoc-gen-ts/src/index.js:60
    const { major = 0, minor = 0, patch = 0 } = request.compiler_version;
            ^

TypeError: Cannot read property 'major' of undefined
    at Object.<anonymous> (/Users/varun/Code/protoc-gen-ts-bug/node_modules/protoc-gen-ts/src/index.js:60:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

Reproduction steps:

1. Download [Buf v1.4.0](https://github.com/bufbuild/buf/releases/tag/v1.4.0) from the releases.
2. `yarn --frozen-lockfile && ./buf generate`, assuming that buf was put in current dir.

The bug doesn't reproduce with `0.8.1`.

```
yarn add --dev protoc-gen-ts@0.8.1 && yarn && ./buf generate # OK

yarn add --dev protoc-gen-ts@0.8.2 && yarn && ./buf generate # FAILS
```

**Comment by thesayyn** [comment]
Hey. thanks for reporting this. Probably Buf does not set the version information for plugins to use. I'll make PR to fix for this but if you have time I'd appreciate it.
The relevant line is here;
https://github.com/thesayyn/protoc-gen-ts/blob/d665bfe69e1c8339cfe1c6f704bdd8b2e5ee22f6/src/index.ts#L119

**Comment by gcurtis** [comment]
I was able to get things working by just leaving the version at 0 if `request.compiler_version` is undefined. I put up a PR for it if you think that approach sounds good.

**Comment by thesayyn** [comment]
Yeap. That was my intention all along. Thanks!

**Comment by varungandhi-src** [comment]
Awesome, thank you for the fix @gcurtis.
