### ISSUE TITLE
Does it support generating ES6 specification JS files and using them in grPC-Web

### ISSUE THREAD

**Issue by yl-yue** [thesayyn/protoc-gen-ts#141]
Does it support generating ES6 specification JS files and using them in grPC-Web

**Comment by thesayyn** [comment]
the plugin itself is not capable of outputting JS files directly. Though you could transpile them via tsc. for gRPC-Web you'll need to change imports manually. See #102

**Comment by thesayyn** [comment]
Feel free to reopen.
