### ISSUE TITLE
.proto3 input -> .ts3 output

### ISSUE THREAD

**Issue by NfNitLoop** [thesayyn/protoc-gen-ts#15]
This worked great out of the box! So much nicer than protoc's commonjs output! ❤️ 

I ran into one odd roadbump -- it kept generating a `.ts3` file, which Snowpack didn't know to interpret as TypeScript. I finally figured out it's because I'd named my file `something.proto3` and that 3 was carried over.  I'm fine just renaming my input file to `.proto` for now to work around this.

**Comment by thesayyn** [comment]
I am glad that you have solved your problem with this plugin. I would appreciate a star though 😄

Also, that is a good catch and I think it is related to this line 
https://github.com/thesayyn/protoc-gen-ts/blob/db9e02e6e2f56d2fa55d21f02b681ed93228ccbd/src/index.js#L1646

I'll fix it this weekend.

**Comment by NfNitLoop** [comment]
>  I would appreciate a star though

Do you mean a GitHub star on the repo? I'd already done that. 😃 👍

**Comment by thesayyn** [comment]
Thank you so much then 😊

**Comment by thesayyn** [comment]
@NfNitLoop Hello again. While I have been working on a fix, I have come to realize that protocol buffers do not support such an extension. At least this was the case for protocol buffers for bazel. Do you have any documentation that I can refer to?

**Comment by thesayyn** [comment]
Nevertheless, I believe that this has been fixed by https://github.com/thesayyn/protoc-gen-ts/commit/d9bfad63d637a6b5990f2b33f9a620172ec0c646.

**Comment by NfNitLoop** [comment]
Thanks!

No, I don't have any official documentation. `protoc` seems happy to parse a file with a `.proto3` extension, though.  And I see [others] using similar filenames.

[others]: https://www.google.com/search?q=".proto3"

**Comment by thesayyn** [comment]
Oh I see. This should be fixed in 0.3.0.
