### ISSUE TITLE
toObject() introducing spurious entries

### ISSUE THREAD

**Issue by jackpunt** [thesayyn/protoc-gen-ts#153]
Ok, it's not toObject() specifically, it's the underlying protobuf Message that asserts a default value for every field?

The change to using getFieldWithDefault() means that toObject() includes all the fields, whether there are defined values in the Message or not.
It was much cleaner before (~0.8.3) where the keys present in output toObject() corresponded to the items actually sent in the message.

But now, providing NO value appears as providing the DEFAULT value (0 for any number, "" for any string) ?!

Q: in the new scheme, is there a way to query a protobuf Message to determine which fields are transmitted?
Q: in the new scheme, is there a way make the 'default' be 'undefined' ?

For my protocol [with 0.8.3] message with { id: 0 } versus { id: undefined } have different meaning.
Do I need to rework to make 0 a special value? (and also "" for strings)?

**Comment by thesayyn** [comment]
Yes with #146 we landed a fix to match the specification. It is a breaking change. 

> Q: in the new scheme, is there a way to query a protobuf Message to determine which fields are transmitted?

yes, every field has a corresponding `has_<field_name>` getter which you can use to query whether field was transmitted.

> Q: in the new scheme, is there a way make the 'default' be 'undefined' ?

no, but it is fairly simple to introduce a new option to have both behaviors. I'd be happy to accept a PR implementing this. 


> Do I need to rework to make 0 a special value? (and also "" for strings)?

I am afraid yes. which makes me wonder whether it is better to have this as an option so a lot of people don't need to change theirs.

**Comment by jackpunt** [comment]
Thanks for the rapid/comprehensive reply 👍 
I'll take a look at `has_<field_name>` (it's mostly for diagnostics, to confirm what msg/fields was created/sent)

**Comment by jackpunt** [comment]
I'm not finding the `has_<field_name>`, probably looking in the wrong place... 
Is it in the published 'api' for protobuf? Can you point me?

I suppose it is something like: 
```
  has_field(n: number): boolean {
    return !jsbp.Message.getFieldWithDefault(this, n, undefined)
  }
```
but that is ugly without having the actual field name.

Hmm, since the generated code still checks for `(val != null)`, I suppose I *could* hack the generated code
to replace the given defaults with 'undefined' where it is important.

My larger problem ATM is the sometimes appearance [or not] of `#one_of_decls: number[][] = [];`
which provokes tsc to declare incompatible types..

**Comment by Santalov** [comment]
> That is interesting. Could you provide a minimal example of `#one_of_decls` causing a problem with the tsc? Perhaps that deserves a separate issue

I am also facing this and some additional problems with tsc, creating a new issue right now. I'd like to contribute to this project.

**Comment by jackpunt** [comment]
> In case you are using `proto3`, you may want to explicitly declare your fields as `optional` 

Thanks; I expect that is where I missed them; I have the minimal proto3, with implicit `optional`

FWIW, I agree with Santalov that the current scheme is correct and Ok, esp considering interop between independent protobuf endpoints. Armed with has_<fieldName> I can make my log files pretty/compact.

**Comment by Santalov** [comment]
> I'll add more about `#private` when I find Santalov's new issue. The basic problem is that it's now impossible to 'subclass' a protobuf class; since there is a #private in each class, the two otherwise compatible types are seen as distinct because the compiler cannot infer anything about the #private fields. There's some related discussion on the typescript project: [microsoft/TypeScript#38953](https://github.com/microsoft/TypeScript/issues/38953) ; (happily that issue is fixed in a future release tsc>4.7.4) I'll know more when I get the other migration issues resolved, probably I'll need to make tsc/js `interface` specs for the shared classes, and not rely on the classes generated by protoc for expressing inheritance.

Sorry, I have misled you. I had a different problem with `#one_of_decls`, which is not related to the #private fields.

**Comment by jackpunt** [comment]
As long as you're here, in other thread you say: `"noImplicitOverride": true,` is supported.
Can you say how to get the needed `override` into the generated .ts ?
(that is: `static override deserializeBinary(bytes: Uint8Array):`)

**Comment by jackpunt** [comment]
Thanks again!
[I cannot imagine why that is not the default]

**Comment by jackpunt** [comment]
Comment: using 'optional' to generate `has_<field>` "works"; by decorating the field as a `one-of`.

A lot of extra clutter in the code... but perhaps I'll just define the has_fieldName getter in my wrapper class, along with the get msgObject() which uses them to make a more representative object than toObject();

Sadly, repeated fields cannot be declared a optional, so all the [] fields still need special treatment. (hmm, maybe i define a slight misleading `has_<repeatedField>` which checks `field.length>0`

**Comment by jackpunt** [comment]
@thesayyn : when there are *other* 'type' problems, tsc includes a complaint about a `#one_of_decls` mismatch.

Happily, when the other type declarations are fixed, tsc says "OH... Ok, looks like you are a subclass, no problem"
so it is very confusing during a refactor, if one can just ignore *that* error and isolate the others, then all is well.

**Comment by thesayyn** [comment]
> [I cannot imagine why that is not the default]

`override` keyword was added to ts recently. That's why we can't make it default and this is the main reason why we have a feature gate for that. If we flip it to true as then default then we'd be confusing people using older versions of typescript. I'd be happy to land documentation improvements (if anyone is up for making a PR) to people find this feature gate easily.

**Comment by thesayyn** [comment]
> when there are _other_ 'type' problems, tsc includes a complaint about a `#one_of_decls` mismatch.

I am not sure what action should be taken to make people's lives easier. I am down for suggestions and fixes.

**Comment by thesayyn** [comment]
> Sadly, repeated fields cannot be declared a optional, so all the [] fields still need special treatment. (hmm, maybe i define a slight misleading `has_<repeatedField>` which checks `field.length>0`

@tomasz-szypenbejl-td  Maybe he has some ideas for improvements here?

**Comment by jackpunt** [comment]
To be clear: I added my own `has_<repeatedField>` which check `length>0`
But is a lie... because sending NO array is different that sending a zero-length array. 
And there is currently no way to distinguish them. 
However, as tomasz says, the wire protocol is efficient so why would anyone really care...?

For me, undefined vs 0-length was helpful to find coding bugs, 
cases where logically/semantically the field should *not* have been included.
(But I can just grep the code more carefully OR just not worry about it)

If I *were* going to submit a code mod, it would be for a flag to generate the `has_fieldName` accessors simply and cleanly without inserting all the optional/one-of code.

(since I have a diff/patch system built into my protoc builder, I can do my own pretty easily,
 but it would be nice to auto-gen them; I just don't like the code-clutter generated by optional/one-of)

**Comment by td-krzysiek** [comment]
Hi @jackpunt,

Protobuf is designed in a way where this is no way to distinguish between empty array and no array, they're basically the same thing. If you "official" serialiser and you set empty array the binary output will be empty too. That's why it doesn't make sense to create has_* messages for repeated fields.

You can try this yourself with the example below.

test.proto
```proto
syntax = "proto3";
message ValuesList {
    repeated int32 values = 1;
}
```
main.js
```js
const { ValuesList } = require('./test_pb');
const v = new ValuesList();
v.setValuesList([])
console.log(v.serializeBinary());
```

```
$ npm init -y
$ npm i google-protobuf
$ protoc test.proto --js_out=import_style=commonjs,binary:.
$ node main.js 
Uint8Array(0) []
```

**Comment by thesayyn** [comment]
Can this be closed?

**Comment by jackpunt** [comment]
Yes, I have inserted the "hadField" methods where necessary/useful
