### ISSUE TITLE
Add support for google.protobuf.Any's pack and unpack methods and correct JSON serialization

### ISSUE THREAD

**Issue by tomasweigenast** [thesayyn/protoc-gen-ts#156]
`.pack` and `.unpack` methods should be implemented and add compatibility with the `toObject` method, to allow JSON serialization.

Another change to be made to the `toObject` method is how it serializes Timestamp and Duration. Timestamp should be serialized to a ISO 8601 string, and Duration to "12m54s", as an example.

**Comment by thesayyn** [comment]
Related to #148

**Comment by thesayyn** [comment]
This is fixed with the rust rewrite.
