### ISSUE TITLE
backwards compatibility `target < ES2017`

### ISSUE THREAD

**Issue by CorrM** [thesayyn/protoc-gen-ts#165]
as [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/Uint8Array#syntax) empty constructor are `ES2017`

![image](https://user-images.githubusercontent.com/5868825/182173489-73c18ed0-2bd0-4a22-978e-40a1ede9ea4e.png)
it could be good to replace that with `new Uint8Array(0)` to support `target < ES2017`

i think its just a small update here [src](https://github.com/thesayyn/protoc-gen-ts/blob/780a31a42a9cb50d69bb9c9534f183fa286351aa/src/descriptor.ts#L1006)

**Comment by thesayyn** [comment]
Do you mind sending a PR?

**Comment by CorrM** [comment]
> Do you mind sending a PR?

#168
