### ISSUE TITLE
Serialized result is inconsistent with Go

### ISSUE THREAD

**Issue by shaneing** [thesayyn/protoc-gen-ts#172]
The message is as follows:

```proto
message SignDoc {
    uint64 account_number = 1;
}
```

And run the following code:

```go
func main() {
	doc := pb.SignDoc{
		AccountNumber: 0,
	}
	bytes, _ := proto.Marshal(&doc)
	fmt.Println(bytes)
}
```

The output is as follows:

```
[]
```

The output is different from the serialized result `[32, 0]` in TypeScript.

**Comment by thesayyn** [comment]
This is due to defaults being serialized. one of PRs that @Santalov put together is going to fix this.

**Comment by thesayyn** [comment]
This is fixed with the rust rewrite as we conform to protobuf conformance tests!
