### ISSUE TITLE
Confusion on generating a .ts file which imports a message from an adjacent file

### ISSUE THREAD

**Issue by ltetreault-va** [thesayyn/protoc-gen-ts#173]
I'm confused about how to generate a .ts file when I have two Protobufs and one imports a message from the first one.

project layout
```tree
project_root/
         protos/
            first.proto
            second.proto
```

**The first file**
```protobuf
syntax="proto3";

option go_package="project/thing";
import "google/protobuf/timestamp.proto";

message AType {
    string things = 1;
}
```

**The second file**

```protobuf
syntax = "proto3";

option go_package="project/thing";
import "protos/first.proto";

message Something {
   types.AType thing = 1;
}
```

I am able to generate the first file fine with 
```command
protoc -I=protos --ts_out=protos/typescript   first.proto
```

but the second one complains about a bad import to the first one
```command
protoc -I=protos --ts_out=protos/typescript   second.proto
```

```command
contact.proto:8:1: Import "protos/first.proto" was not found or had errors.
contact.proto:17:9: "AType" is not defined.
```

I'm guessing I'm missing something in my command but I am not sure what.

**Comment by thesayyn** [comment]
`-I=protos` is the problem here. your imports should be relative to that. so instead of importing instead of `protos/first.proto` use `first.proto`.
