### ISSUE TITLE
Cannot deserialize maps with empty K/V encoded by other language implementations

### ISSUE THREAD

**Issue by gwy15** [thesayyn/protoc-gen-ts#175]
Hello. I'm using protoc-gen-ts to deserialize pbs encoded by other languages (specifically, by Rust prost) and it gives the following error:
```
Error: 13 INTERNAL: Response message parsing error: Assertion failed
```

# How to reproduce
for this protobuf,
```protobuf
syntax = "proto2";

message Message {
    map<string, string> map = 1;
}
```
and data
```js
{
 map: { keya: "a", keyb: "" }
}
```

Rust generates the following binary hex: `0a090a046b6579611201610a060a046b657962`
which translates to 
![image](https://user-images.githubusercontent.com/23229760/191884041-0620b898-0dbe-4c18-af17-1f793bae4234.png)

# Possible reason
The reason is that, when serializing a map with empty K/V, in this case an empty V, google states that

> If you provide a key but no value for a map field, the behavior when the field is serialized is language-dependent. In C++, Java, Kotlin, and Python the default value for the type is serialized, while in other languages nothing is serialized.

Rust choose to skip serializing anything at all, while protoc-gen-ts implementation throws exception (i.e. the Assertion failed) when trying to deserializing map bytes with missing K/V.

**Comment by thesayyn** [comment]
I don't know what should be the behavior when there is no `K` but i agree that we shouldn't be throwing when `V` is missing.

**Comment by thesayyn** [comment]
This is fixed with the rust rewrite.
