### ISSUE TITLE
Request: Show How to Properly Do Client-Server Communication in Example

### ISSUE THREAD

**Issue by flolu** [thesayyn/protoc-gen-ts#18]
with [grpc-node](https://github.com/grpc/grpc-node)

**Comment by thesayyn** [comment]
We have a tiny not so understandable example in our tests https://github.com/thesayyn/protoc-gen-ts/blob/master/test/integration/rpcs.spec.ts right here. However, it would be good to have a working example in the examples folder. 

Would you like to send a PR for it?

**Comment by flolu** [comment]
@thesayyn Awesome! I will make a PR if I get it working :)

**Comment by flolu** [comment]
@thesayyn Before creating the PR I wanted to make it work myself. However, I encountered a few issues:

You can also follow along with [this repro](https://github.com/flolu/typescript-protobuf-bazel-rpc)

## 1. grpc binary doesn't load
For some reason I get this error _(running `yarn dev` in the repro)_
```
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v72-linux-x64-musl
Found: [node-v64-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-musl/grpc_node.node'
```
The [internet](https://stackoverflow.com/questions/49758008/nodejs-error-failed-to-load-grpc-binary-module-because-it-was-not-installed-fo) says it can be fixed by reinstalling or running `npm rebuild`. This didn't help me.

The only solution I was able to find is to use [@grpc/grpc-js](https://www.npmjs.com/package/@grpc/grpc-js) instead of [grpc](https://www.npmjs.com/package/grpc)

_:thinking:  Is it feasible to make that change internally?_ Because this would require removing `grpc` as a direct dependency and switching it out with @grpc/grpc-js

## 2. Typescript strict mode not compatible
To get IntelliSense in my IDE I added this path to the `tsconfig.json`
```
"paths": {
  "@repro/*": ["bazel-bin/*"]
}
``` 
![Screenshot from 2020-09-16 08-44-36](https://user-images.githubusercontent.com/34191949/93301537-e4280700-f7f8-11ea-9b77-95488da772bb.png)
But as you can see in the picture, Typescript doesn't like the generated code in `"strict": true` mode. _(you can try it by setting `"strict": true` in the `tsconfig.json` of the repro)_


## 3. local development with docker-compose not possible
Let's assume the first and second issue are resolved. (you can try it yourself by changing the generated code (`bazel-bin/example.ts`) to import from `@grpc/grpc-js` instead of `grpc` and then running `yarn dev`)

This line
```
import {ExampleClient, Request} from '@repro/example'

const client = new ExampleClient('repro_server:9090', grpc.credentials.createInsecure())
```

still throws an error:
```
repro_client | TypeError: Class constructor ServiceClientImpl cannot be invoked without 'new'
repro_client |     at new ExampleClient (/bazel-bin/example.ts:129:5)
repro_client |     at Object.<anonymous> (/client.ts:5:16)
repro_client |     at Module._compile (internal/modules/cjs/loader.js:1137:30)
repro_client |     at Module._compile (/node_modules/source-map-support/source-map-support.js:547:25)
repro_client |     at Module.m._compile (/tmp/ts-node-dev-hook-22284816646158.js:57:33)
repro_client |     at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
repro_client |     at require.extensions.<computed> (/tmp/ts-node-dev-hook-22284816646158.js:59:20)
repro_client |     at Object.nodeDevHook [as .ts] (/node_modules/ts-node-dev/lib/hook.js:63:13)
repro_client |     at Module.load (internal/modules/cjs/loader.js:985:32)
repro_client |     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
repro_client | [ERROR] 06:47:10 TypeError: Class constructor ServiceClientImpl cannot be invoked without 'new'
```
Maybe that's because I've changed the code to import from `@grpc/grpc-js`?

---

**Conclusion**
I really like Protobuf. But for me it is only feasible to use in combination with Typescript. And I need it to work for local development with docker-compse.

But I've already spent too much time trying to get it working and it hurts my productivity.
If those issues above are non-trivial to fix I will probably need to go back to just using HTTP/json requests instead of gRPC :disappointed:

**Comment by thesayyn** [comment]
You are right. I have also spent more than 2 weeks to get it working in typescript environment then i couldn't. therefore i have decided to make a plugin that generates the protobuf classes that works with typescript with minimum fuss.

That said, i think solving the problems with native packages is not trivial. I feel you. As far as i know grpc module is deprecated and does not receive any new features. So i think this plugin should use @grpc/grpc-js instead of grpc. Or may be we could add an option for it so that folks could use whichever they want.

About strict mode, i haven't used the generated files with strict mode flipped so there could be some problems but i don't think that they too hard to solve. Maybe i could flip the strict mode in our tests so that we could catch any issues with strict mode.

Also, i would like to make a 1:1 pair programming to solve your problems if that works for you too. 😊

**Comment by flolu** [comment]
@thesayyn Exactly, this is why I would love to use your plugin!

If grpc is deprecated anyhow, then it might be worth switching over to @grpc/grpc-js?

Yeah strict mode should be solvable.

Would love to do a 1:1, because I am somewhat stuck on it. When are you free? Over Discord?

**Comment by thesayyn** [comment]
Today (Wed) at  4PM UTC? Would that work for you?

**Comment by flolu** [comment]
@thesayyn Sounds good! My discord username is: `flolu#6889`

**Comment by flolu** [comment]
I've created a pull request with an example implementation https://github.com/thesayyn/protoc-gen-ts/pull/21
