### ISSUE TITLE
Solo enum in the proto file case a bad field type name

### ISSUE THREAD

**Issue by CorrM** [thesayyn/protoc-gen-ts#180]
When i have one enum(maybe more than one too) on the whole file that will case a bad filed type name.

After checking src i think the bug would be in that function [field.getType](https://github.com/thesayyn/protoc-gen-ts/blob/main/src/field.ts#L36)

**Sorry im so busy this days, i can't submit PR**

**Bug showcase**:
```
// update-prop-message.ts
// enumUpdatePropChangeEnum MUST to be UpdatePropChangeEnum
set change_type(value: dependency_1.enumUpdatePropChangeEnum) {
        pb_1.Message.setField(this, 1, value);
}
```

**Files to raise the bug**:
```
// update-prop-change-enum.proto
syntax = "proto3";

package MY_PACKAGE.enum;

enum UpdatePropChangeEnum
{
  UpdatePropChange_NONE = 0;
  CHANGE = 1;
}
```

```
// update-prop-message.proto
syntax = "proto3";

package MY_PACKAGE.message;

import "update-prop-change-enum.proto";

message UpdatePropMessage
{
  MY_PACKAGE.enum.UpdatePropChangeEnum change_type = 1;
}
```

**Comment by CorrM** [comment]
any update ?

**Comment by thesayyn** [comment]
Hey, no. Please feel free to send a PR.

**Comment by CorrM** [comment]
I never uses bazel before, and development section in readme is are poor (at least for me) sorry,
if you can show me how to setup the dev environment i could fix it. <3

**Comment by thesayyn** [comment]
This is fixed in the rust implementation; See https://github.com/thesayyn/protoc-gen-ts/issues/255
