### ISSUE TITLE
Feature Request: Simple type vaildate for `fromObject`

### ISSUE THREAD

**Issue by way-zer** [thesayyn/protoc-gen-ts#186]
For array and `Message`, it is Ok, vaildate throught `forEach` and child `fromObject`.

But for base type, it may be wrong, like:
* Array would be set to a string field.
* String would be set to a enum field.
* May be more.

I'm using with `pb-text-format-to-json`, there are two problem:
* repeated field may get a object: convert to array with single item.
* enum field get string: convert name to number.

**Comment by thesayyn** [comment]
This should be fixed with the rust rewrite. could you confirm that?
