### ISSUE TITLE
fromObject does not check for nullables when mapping

### ISSUE THREAD

**Issue by johnnyasantoss** [thesayyn/protoc-gen-ts#188]
I have a proto file that depends on `google/api/protobuf/descriptor` (I'm using definitions from `google-proto-files=3.0.2` package) and building it like so:
`protoc -I=./node_modules/google-proto-files/ -I=. --ts_opt=unary_rpc_promise=true --ts_opt=no_namespace --ts_out=./src/generated rpc.proto`

It does work and generates various ts files, but all `fromObject` methods that interact with arrays (those in the `descriptor` proto file) have an error that prevent me from "compiling" ts.

```log
src/generated/google/protobuf/descriptor.ts:28:19 - error TS2532: Object is possibly 'undefined'.

28             file: data.file.map(item => FileDescriptorProto.fromObject(item))
                     ~~~~~~~~~

src/generated/google/protobuf/descriptor.ts:233:27 - error TS2532: Object is possibly 'undefined'.

233             message_type: data.message_type.map(item => DescriptorProto.fromObject(item)),
                              ~~~~~~~~~~~~~~~~~
...
```

Adding conditional access `?.` and a default `?? []`  would already make it work

I'm just getting started with protoc so any recommendations are welcome :)

**Comment by johnnyasantoss** [comment]
```diff
diff --git a/src/descriptor.ts b/src/descriptor.ts
index f70441d..e9d53b5 100644
--- a/src/descriptor.ts
+++ b/src/descriptor.ts
@@ -188,10 +188,17 @@ function createFromObject(
             [ts.factory.createIdentifier("item")],
           ),
         );
-        assignmentExpr = ts.factory.createCallExpression(
-          ts.factory.createPropertyAccessExpression(assignmentExpr, "map"),
-          undefined,
-          [arrowFunc],
+        assignmentExpr = ts.factory.createBinaryExpression(
+          ts.factory.createCallExpression(
+            ts.factory.createPropertyAccessChain(assignmentExpr, ts.factory.createToken(ts.SyntaxKind.QuestionDotToken), "map"),
+            undefined,
+            [arrowFunc],
+          ),
+          ts.factory.createToken(ts.SyntaxKind.QuestionQuestionToken),
+          ts.factory.createArrayLiteralExpression(
+            [],
+            false
+          )
         );
       } else {
         assignmentExpr = ts.factory.createCallExpression(
```

Would adding such a change be a proper fix? I have no experience with ts factory

This would only change the codegen for repeated messages

**Comment by thesayyn** [comment]
Do you mind sending a PR so we can what the output of this change?

**Comment by johnnyasantoss** [comment]
hey @thesayyn just created #202, let me know if that has any value. It does add a default but I'm not sure if it is a proper fix.
