### ISSUE TITLE
Migrate away from grpc to @grpc/grpc-js

### ISSUE THREAD

**Issue by flolu** [thesayyn/protoc-gen-ts#19]
_We have already talked about it. This just serves as a reminder._

The [grpc](https://www.npmjs.com/package/grpc) package is more or less deprecated. Thus we should migrate to using [@grpc/grpc-js](https://www.npmjs.com/package/@grpc/grpc-js) instead.

But it might not be enough to just interchange them. Since it seems as if there are small incompatibilities.

**Comment by thesayyn** [comment]
Releases in 0.3.1

**Comment by flolu** [comment]
That was fast, thank you!
