### ISSUE TITLE
Typescript 5 breaking compilation

### ISSUE THREAD

**Issue by khang-at-sri** [thesayyn/protoc-gen-ts#197]
It appears the version for Typescript wasn't locked down which allowed the installation of Typescript 5 instead of 4.x when doing a fresh `npm install -g`.  This breaks the compilation process, producing an error along the lines of: 

`TypeError: Cannot create property 'pos' on string 'fields'`

**Comment by curquhart** [comment]
+1

**Comment by SKTT1Ryze** [comment]
+1
https://code.mycard.moe/mycard/neos-protobuf/-/jobs/82799

**Comment by SKTT1Ryze** [comment]
How can i solve this problem?

**Comment by LucasXu0** [comment]
+1

**Comment by thesayyn** [comment]
I can confirm. Does anybody mind sending a PR for it?

**Comment by SKTT1Ryze** [comment]
> I can confirm. Does anybody mind sending a PR for it?

I manually replace the version of `typescript` in `/Users/username/.nvm/versions/node/v18.9.0/lib/node_modules/protoc-gen-ts/package.json` with 4.9.x and it works:
```json
{
    ...
    "devDependencies": {
    ...
    "typescript": "^4.3.4" -> "4.9.x"
  }
}
```

Should we solve this issue by this way?

And it seems that it's a problem within `0.8.5` release, not the `main` branch. Do you mean a PR for `0.8.5` release branch?

**Comment by thesayyn** [comment]
that's the principled fix here. main also has this problem.

NOTE: typescript has been causing a lot of problems lately. I'll ship it bundled.

**Comment by xqi-aviatrix** [comment]
+1. Can anyone help fix the issue in the code and publish a release.
We are hitting the issue in our github workflow where we have little control about the installed libs.

**Comment by LucasXu0** [comment]
FYI. Here's a workaround.

```
npm install -g protoc-gen-ts typescript@4.9.5
```
