### ISSUE TITLE
[jstype = JS_STRING]  type Compile error

### ISSUE THREAD

**Issue by chenxyzl** [thesayyn/protoc-gen-ts#2]
`int64 result_per_page = 3 [jstype = JS_STRING];`

Still compiled to number

`      get result_per_page(): number | undefined {
            return pb_1.Message.getFieldWithDefault(this, 3, undefined) as number | undefined;
        }  
`
`
        set result_per_page(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
`

**Comment by thesayyn** [comment]
Thank you for the issue and that is something we should be able to do since Javascript does not support 64-bit integers. I will add this to the roadmap. Also, PR is appreciated if you can send one :)

**Comment by chenxyzl** [comment]
I'm going to do it at this weekend。

**Comment by chenxyzl** [comment]
“[jstype = JS_STRING]” support already added；
But I don't know how to test on the new version；

**Comment by thesayyn** [comment]
Hey @chenxyzl just send a PR. I will assist you in testing.

**Comment by chenxyzl** [comment]
OK, PR submitted

**Comment by thesayyn** [comment]
closed by #57
