### ISSUE TITLE
Cannot use in bazel project as no BUILD file

### ISSUE THREAD

**Issue by Gentatsu** [thesayyn/protoc-gen-ts#201]
When I try to load the package, I get this error:
```
 every rule of type ts_proto_library_ implicitly depends upon the target '//protoc-gen-ts/bin:protoc-gen-ts', but this target could not be found because of: no such package 'protoc-gen-ts/bin': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
```

Loading in like this:
`load("//:node_modules/protoc-gen-ts/index.bzl", "ts_proto_library")`

Any ideas?

**Comment by thesayyn** [comment]
protoc-gen-ts doesn't support rules_js yet. https://github.com/thesayyn/protoc-gen-ts/tree/rules_js is getting there. I need funding to get it there fully.

**Comment by thesayyn** [comment]
This is not relevant anymore as we no longer expose a bazel rule.
