### ISSUE TITLE
Directly include generated ts file as dependency in ts_project

### ISSUE THREAD

**Issue by darkpursuer** [thesayyn/protoc-gen-ts#207]
I wonder if there is any way for us to directly include the generated ts file in the ts_project as a dependency, instead of copy it manually from the bazel-bin.

An alternative way is to write a cmd to automatically generate and copy the ts files.

**Comment by thesayyn** [comment]
Hey, sorry that i let this linger long. We no longer expose a bazel rule here. rules_ts has a ts_proto_library that could support protoc-gen-ts. 

Closing as not relevant anymore
