### ISSUE TITLE
Generation with target=web

### ISSUE THREAD

**Issue by Hartigan** [thesayyn/protoc-gen-ts#218]
Hi
I use `protoc-gen-ts` for generation typescript code for grpc service for webpage:

```
protoc \
    --ts_out=./generated \
    --ts_opt=target=web \
    --ts_opt=unary_rpc_promise=true \
    sample.proto
```

But generated code contains `import * as grpc_1 from "@grpc/grpc-js";` and `grpc-js` definitions. I expect only `grpc-web` definitions with `target=web` option

**Comment by scippio** [comment]
I have a same problem :( I don't know haw generate code for using in my web app. I still getting: ` process is not defined`

**Comment by thesayyn** [comment]
Unfortunately, we don't have the switch to only generate client code vs server code. PRs welcome.

**Comment by thesayyn** [comment]
This is fixed with the rust rewrite.
