### ISSUE TITLE
Experimental Promises Do Not Work (Cannot read property 'interceptors' of undefined)

### ISSUE THREAD

**Issue by flolu** [thesayyn/protoc-gen-ts#22]
After enabling `experimental_features`, I get the following error:
```
TypeError: Cannot read property 'interceptors' of undefined
    at ExampleClient.makeUnaryRequest (app/client_image.binary.runfiles/npm/node_modules/@grpc/grpc-js/src/client.ts:295:52)
    at ExampleClient.add (app/client_image.binary.runfiles/npm/node_modules/@grpc/grpc-js/src/make-client.ts:174:15)
    at example.ts:123:61
    at new Promise (<anonymous>)
    at ExampleClient.add (example.ts:123:16)
    at client.ts:17:33
    at Generator.next (<anonymous>)
    at /app/client_image.binary.runfiles/repro/client.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/app/client_image.binary.runfiles/repro/client.js:3:12)
```

You can try it yourself by cloning this commit:
https://github.com/flolu/typescript-protobuf-bazel-rpc/tree/8f1c47cb9944064384e9f87db2c30f0a98a2b6a2

1. Run `yarn install && yarn build`
2. Run `yarn start:server`
3. Run `yarn start:client` (error is in the client)

**Comment by thesayyn** [comment]
Hey, Thank you for reporting this. I have added this to my backlog.

**Comment by thesayyn** [comment]
Hey @flolu 

Could please try this again with the latest version of the plugin. it should be working

Feel free to reopen if the problem persists

**Comment by maZahaca** [comment]
I've just installed the latest version `0.3.8` and it seems that the issue is still there:

```
TypeError: Cannot read property 'interceptors' of undefined

      1366 |         }
      1367 |         CreateAccount(request: Request, metadata?: grpc_1.Metadata): Promise<Response> {
    > 1368 |             return new Promise((resolve, reject) => super["CreateAccount"](request, metadata, (error: grpc_1.ServiceError, response: Response) => {
           |                                                                           ^
      1369 |                 if (error) {
      1370 |                     reject(error);
```

@thesayyn any thoughts what could be the root of this issue?

**Comment by maZahaca** [comment]
@thesayyn

Btw, when no promises version the call looks like the following, and it works well.

```
...
client['CreateAccount'](
   new proto.namespace_test.Request(),
   callback,
);
```

as you can see there is no `metadata` parameter in the middle of params compare to Promise version.

**Comment by thesayyn** [comment]
Hey @maZahaca 

Could you please provide some additional information such as the version of the "google-protobuf" and "@grpc/grpc-js" or "grpc" that you are using?

**Comment by maZahaca** [comment]
sure @thesayyn, here is my `package.json`:

```
{
  "dependencies": {
    "@grpc/grpc-js": "^1.3.4",
    "google-protobuf": "^3.15.5"
  },
  "devDependencies": {
    "@types/google-protobuf": "^3.15.0",
    "@types/node": "^15.12.4",
    "protoc-gen-ts": "^0.3.8",
    "typescript": "^4.3.4"
  }
}
```

**Comment by thesayyn** [comment]
It is so strange that i can not reproduce this problem.

**Comment by kluiverjh** [comment]
Got the same error. When I generate the proto code in the non experimental way; and apply manual the promise as done in the experimental mode I can reproduce the problem. When the meta data is passed in as null, the error "Cannot read property 'interceptors' of undefined" is returned.

This returns the 'Cannot read property 'interceptors' of undefined'
WithMeta_promise(request, meta) {
    return new Promise((resolve, reject) =>
      this.client['CreateAccount'](
        request,
        meta,
        (error, response) => {
          if (error) {
            reject(error);
          } else {
            resolve(response);
          }
        },
      ),
    );
  }
This doesn't returns the 'Cannot read property 'interceptors' of undefined'
WithoutMeta_promise(request) {
    return new Promise((resolve, reject) =>
      this.client['CreateAccount'](
        request,
        (error, response) => {
          if (error) {
            reject(error);
          } else {
            resolve(response);
          }
        },
      ),
    );
  }

**Comment by thesayyn** [comment]
> Got the same error. When I generate the proto code in the non experimental way; and apply manual the promise as done in the experimental mode I can reproduce the problem. When the meta data is passed in as null, the error "Cannot read property 'interceptors' of undefined" is returned.
> 
> This returns the 'Cannot read property 'interceptors' of undefined'
> WithMeta_promise(request, meta) {
> return new Promise((resolve, reject) =>
> this.client['CreateAccount'](
> request,
> meta,
> (error, response) => {
> if (error) {
> reject(error);
> } else {
> resolve(response);
> }
> },
> ),
> );
> }
> This doesn't returns the 'Cannot read property 'interceptors' of undefined'
> WithoutMeta_promise(request) {
> return new Promise((resolve, reject) =>
> this.client['CreateAccount'](
> request,
> (error, response) => {
> if (error) {
> reject(error);
> } else {
> resolve(response);
> }
> },
> ),
> );
> }

I have suspected this. Great finding!

Perhaps we add some overloads to this function and have a conditional call based on the availability of variables.

I would welcome a PR if you are up to it.

**Comment by maZahaca** [comment]
So, if `metadata` is not passed are we gonna create a new empty one?

**Comment by thesayyn** [comment]
Nope. if the metadata is not present we not gonna pass it at all just to be safe.

If it does not hurt to pass it, we can just construct a new one whenever the metadata is empty but I am not sure about the internal behavior of metadata argument and what would happen if we were to pass an empty one. 

so it would look like this

```typescript

method(request: RequestType): Promise<ResponseType>
method(request: RequestType, metadata: Metadata): Promise<ResponseType>
method(request: RequestType, metadata?: Metadata): Promise<ResponseType>

client.method(new RequestType());
client.method(new RequestType(), new Metadata())
```

and the implementation would look like;

```typescript
if (metadata) {
   super.get(request, metadata, callback);
} else {
  super.get(request, metadata, callback);
}
```

**Comment by maZahaca** [comment]
Anytime soon we can have this implemented? I took a look into the code and realized that I'm not too familiar with it.

**Comment by thesayyn** [comment]
@maZahaca I will try to implement it today.

**Comment by thesayyn** [comment]
#72 already fixes this problem but it introduces some breaking.

**Comment by thesayyn** [comment]
https://github.com/thesayyn/protoc-gen-ts/releases/tag/0.3.9 has been released. 

This is fixed in the new release.
