### ISSUE TITLE
Cannot use ‘in’ operator to search for ‘Array’ in undefined；

### ISSUE THREAD

**Issue by KevinIsACoder** [thesayyn/protoc-gen-ts#221]
I got typescript file success, but got this error, when run

**Comment by KevinIsACoder** [comment]
![1691481738126](https://github.com/thesayyn/protoc-gen-ts/assets/35457784/6b62c576-bf7a-4973-bfc9-d6d650318692)

**Comment by thesayyn** [comment]
This is fixed with the rust rewrite.
