### ISSUE TITLE
npm package needs publishing to include fix for typescript >= 5

### ISSUE THREAD

**Issue by wdoconnell** [thesayyn/protoc-gen-ts#225]
This PR https://github.com/thesayyn/protoc-gen-ts/pull/204 (April 1 2023) fixed a check that was causing protoc-gen-ts to decline to run if the user had a typescript version above 5. The fix is in, but protoc-gen-ts and plugins that rely on it won't work until the npm package is updated.

https://www.npmjs.com/package/protoc-gen-ts (last updated Mar. 2023)

**Comment by drbild** [comment]
Does this [peerDependency](https://github.com/thesayyn/protoc-gen-ts/blob/b6bbc9c8dc30b5e0007a4268dd893e470f492f96/package.json#L29C8-L29C8) need to be updated as well?

**Comment by wdoconnell** [comment]
Yes, I think so

**Comment by wdoconnell** [comment]
Which folks have authority to handle npm publication?

**Comment by thesayyn** [comment]
> Does this [peerDependency](https://github.com/thesayyn/protoc-gen-ts/blob/b6bbc9c8dc30b5e0007a4268dd893e470f492f96/package.json#L29) need to be updated as well?

Can somebody send a PR for this? I'll cut a release after the fix lands.

**Comment by wdoconnell** [comment]
@thesayyn thanks very much - I'll push up a PR tomorrow.

**Comment by wdoconnell** [comment]
@thesayyn All set - added a PR for this.

**Comment by wdoconnell** [comment]
@thesayyn Is it possible for you to cut a new npm release now that this is merged? Thanks very much.

**Comment by thesayyn** [comment]
https://github.com/thesayyn/protoc-gen-ts/releases/tag/0.8.7 is up
