### ISSUE TITLE
The namespace 'Google protobuf' does not have an exported member 'BinaryWriter'

### ISSUE THREAD

**Issue by binbin1760** [thesayyn/protoc-gen-ts#228]
![err](https://github.com/thesayyn/protoc-gen-ts/assets/73382349/bb5a5b05-4285-4d48-81f0-b59e92b8fd3b)

first use!  thanks
hero  please！

**Comment by thesayyn** [comment]
This is fixed in the rust implementation. See: https://github.com/thesayyn/protoc-gen-ts/issues/255
