### ISSUE TITLE
import_style=es6 ?

### ISSUE THREAD

**Issue by ivegotwings** [thesayyn/protoc-gen-ts#244]
Can I use `import_style=es6 `? I tried using it, when I compare the diff from `commonjs` I see all the imports removed. Since there are no imports it's causing errors.

<img width="1419" alt="Screenshot 2023-12-13 at 11 20 49 AM" src="https://github.com/thesayyn/protoc-gen-ts/assets/11781585/f056e69e-858b-4505-996b-ae615a036813">

The compilation works fine, at runtime I get the error `goog` is not defined.

**Comment by thesayyn** [comment]
protoc-gen-ts doesn't have such option and the generated code doesn't seem to be generated by protoc-gen-ts.
