### ISSUE TITLE
Compiler fails to build typescript proto definitions

### ISSUE THREAD

**Issue by filipe-costa** [thesayyn/protoc-gen-ts#25]
I am trying to compile the TS definitions according to the documentation, but I have encountered some issues when running the following command:

```
protoc \
    --ts_out=grpc_js:../autogen \
    -I ./proto \
    ./proto/*.proto
```

The script fails and exists with the following message:
```
--ts_out: protoc-gen-ts: Plugin failed with status code 1.
```

As you can see on the following screenshot:

![image](https://user-images.githubusercontent.com/25135035/95680210-bfdd0180-0bcf-11eb-96a6-1764387839c6.png)

My dependencies are the following:

```
  "dependencies": {
    "@grpc/grpc-js": "^1.1.7",
    "@grpc/proto-loader": "^0.5.5",
    "@types/google-protobuf": "^3.7.3",
    "@types/node": "^14.11.8",
    "google-protobuf": "^3.13.0",
    "ts-node-dev": "^1.0.0-pre.63",
    "typescript": "^4.0.3"
  },
  "devDependencies": {
    "grpc-tools": "^1.9.1",
    "grpc_tools_node_protoc_ts": "^5.0.0",
    "protoc-gen-ts": "^0.3.4"
  }
```

My tsconfig file definition is the following:

```
{
    "compilerOptions": {
      "moduleResolution": "node",
      "module": "commonjs",
      "target": "ES6",
      "noImplicitAny": true,
      "removeComments": true,
      "preserveConstEnums": true,
    },
    "exclude": ["node_modules", "**/*.spec.ts"]
}
```

**Comment by filipe-costa** [comment]
My apologies, there was a conflict of dependencies between ```protoc-gen-ts and grpc-tools```, most probably related to the path where the dependency was at.

The solution was to remove ```protoc-gen-ts``` all together.

I am now just using:
```
grpc_tools_node_protoc \
    --js_out=import_style=commonjs,binary:"../autogen" \
    --grpc_out="grpc-js:../autogen" \
    -I ./proto \
    ./proto/*.proto

grpc_tools_node_protoc \
    --ts_out="grpc-js:../autogen" \
    -I ./proto \
    ./proto/*.proto
```

I will close this issue now.

**Comment by thesayyn** [comment]
HI. For your information, this plugin generates the typescript code rather than the definitions alone. If you are using this plugin, you don't need any other plugins to make grpc work with typescript. I should have made it clear in the readme.
