### ISSUE TITLE
[rust] Error starting the proto build with new rust wasm package. Error when executing /usr/bin/protoc-gen-ts

### ISSUE THREAD

**Issue by plachta11b** [thesayyn/protoc-gen-ts#251]
Missing line `#!/usr/bin/env node` in `js/plugin/main.js` file.

I built this package locally from the rust source. Steps leading to reproducing to execution error:

- `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
- `npm install -g wasm-pack`
- `apt install pkg-config libssl-dev`
- `wasm-pack build --out-dir js/plugin/dist --target nodejs --no-pack --out-name plugin`
- `npm install --force -g .`

Protoc version: `libprotoc 25.1` (ubuntu image)

Version: main-7a6a5473

**Comment by thesayyn** [comment]
Yes, this looks like a bug. PRs are welcome.
