### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of null

### ISSUE THREAD

**Issue by CMCDragonkai** [thesayyn/protoc-gen-ts#27]
Attempting to use this plugin with `grpc-tools` from `grpc-node` package:

```
protoc \
  --proto_path=proto/schemas \
  --plugin=protoc-gen-grpc="$(which grpc_node_plugin)" \
  --js_out=import_style=commonjs,binary:proto/js \
  --ts_out="proto/js" \
  --grpc_out=grpc_js:proto/js \
  ./proto/schemas/*.proto
```

Results in:

```
/home/cmcdragonkai/Projects/js-polykey/node_modules/typescript/lib/typescript.js:12449
        return array.hasOwnProperty("pos") && array.hasOwnProperty("end");
                     ^

TypeError: Cannot read property 'hasOwnProperty' of null
    at Object.isNodeArray (/home/cmcdragonkai/Projects/js-polykey/node_modules/typescript/lib/typescript.js:12449:22)
    at createNodeArray (/home/cmcdragonkai/Projects/js-polykey/node_modules/typescript/lib/typescript.js:20812:25)
    at Object.createCallExpression (/home/cmcdragonkai/Projects/js-polykey/node_modules/typescript/lib/typescript.js:22099:95)
    at Object.createCall (/home/cmcdragonkai/Projects/js-polykey/node_modules/typescript/lib/typescript.js:3022:29)
    at createToObject (/home/cmcdragonkai/Projects/js-polykey/node_modules/protoc-gen-ts/index.js:49:14)
    at createMessage (/home/cmcdragonkai/Projects/js-polykey/node_modules/protoc-gen-ts/index.js:1016:5)
    at processMessageDescriptor (/home/cmcdragonkai/Projects/js-polykey/node_modules/protoc-gen-ts/index.js:1545:5)
    at processProtoDescriptor (/home/cmcdragonkai/Projects/js-polykey/node_modules/protoc-gen-ts/index.js:1590:12)
    at main (/home/cmcdragonkai/Projects/js-polykey/node_modules/protoc-gen-ts/index.js:1680:24)
    at Object.<anonymous> (/home/cmcdragonkai/Projects/js-polykey/node_modules/protoc-gen-ts/index.js:1765:1)
--ts_out: protoc-gen-ts: Plugin failed with status code 1.
```

**Comment by CMCDragonkai** [comment]
Using latest typescript 4.1.3. Is this compatible with the latest typescript?

**Comment by thesayyn** [comment]
Hey @CMCDragonkai. in lock file we have `^3.8.3` and i think it ought to work with 4.x.x.  

But we have something else to fix here. as far as i can see that you are trying to use this with other plugins. I guess you understood the plugin wrong. You don't need any other `JS` related plugins if you are using this plugin. 

so instead of you way you should use it like this;

`protoc
  --proto_path=proto/schemas 
  --ts_out="proto/ts" 
  ./proto/schemas/*.proto`
  
it will generate everything to the 'proto/ts' directory. you can import those files and they are ready to use.
keep in mind that in that directory theres `.ts` files instead of `.d.ts` files which means they contain all the necessary runtime code to run.
I would like assist you further if you can't get out of this situation.

**Comment by CMCDragonkai** [comment]
Wait are you saying protoc-gen-grpc is not needed?

That tool is provided by the grpc-node package.

**Comment by thesayyn** [comment]
> Wait are you saying protoc-gen-grpc is not needed?
> 
> That tool is provided by the grpc-node package.

Exactly. This  plugin will also generate service classes if your proto file contains any rpcs.

**Comment by CMCDragonkai** [comment]
Hi @thesayyn can you update the `typescript` to be `4.x.x` or allow the major version to vary?

**Comment by CMCDragonkai** [comment]
How does?

```
protoc --proto_path=proto/schemas --ts_out="proto/ts" ./proto/schemas/*.proto
```

Know about the plugin at all?

Do we need to use `$(which protoc-gen-ts)`?

**Comment by CMCDragonkai** [comment]
So I got super confused. https://github.com/thesayyn/protoc-gen-ts/blob/master/src/package.json <- this is the actual package.json.

But we are using `protoc` from `grpc-tools`. I'm not sure if your `protoc` mentioned above is from upstream `protobuf` or something else.

Furthermore it's not really clear how `protoc` is meant to know about `protoc-gen-ts`.

**Comment by robert-cronin** [comment]
> Hey @CMCDragonkai. in lock file we have `^3.8.3` and i think it ought to work with 4.x.x.
> 
> But we have something else to fix here. as far as i can see that you are trying to use this with other plugins. I guess you understood the plugin wrong. You don't need any other `JS` related plugins if you are using this plugin.
> 
> so instead of you way you should use it like this;
> 
> `protoc --proto_path=proto/schemas --ts_out="proto/ts" ./proto/schemas/*.proto`
> 
> it will generate everything to the 'proto/ts' directory. you can import those files and they are ready to use.
> keep in mind that in that directory theres `.ts` files instead of `.d.ts` files which means they contain all the necessary runtime code to run.
> I would like assist you further if you can't get out of this situation.

I am now confused as well, using the command you suggested results in a generation of `.d.ts` files not `.ts` files:

```
AD+rcronin9@DESKTOP-GTR8EMA MINGW64 ~/Documents/github/js-polykey (polykey-app-bugs)
$ ls ./src/proto/ts

AD+rcronin9@DESKTOP-GTR8EMA MINGW64 ~/Documents/github/js-polykey (polykey-app-bugs)
$ protoc --proto_path=src/proto/schemas --ts_out="src/proto/ts" src/proto/schemas/Agent.proto 

AD+rcronin9@DESKTOP-GTR8EMA MINGW64 ~/Documents/github/js-polykey (polykey-app-bugs)
$ ls ./src/proto/ts
Agent_grpc_pb.d.ts  Agent_pb.d.ts
```

**Comment by thesayyn** [comment]
> Hi @thesayyn can you update the `typescript` to be `4.x.x` or allow the major version to vary?

I got a relocation thing going on so i won't be able to work on this for a month or so. it would be great if you could send a PR for it.

**Comment by thesayyn** [comment]
> How does?
> 
> ```
> protoc --proto_path=proto/schemas --ts_out="proto/ts" ./proto/schemas/*.proto
> ```
> 
> Know about the plugin at all?
> 
> Do we need to use `$(which protoc-gen-ts)`?


First: So when you install this plugin globally through `npm i -g protoc-gen-ts` it installs the plugin to a global location which in turn will be available as a command. Normally after a global installation you can test if the plugin installed by running `protoc-gen-ts` command in your terminal. Though the plugin is not ought to work standalone. It has to be invoked by the `protoc` compiler. 

Answer to the question "how the compiler know about the plugin" is pretty simple.
when you invoke the compiler like 
`protoc --ts_out` the compiler find every option that ends with `*_out` and then looks up to the path to find a command that matches string where the wilcard is. So in this case the compiler will look up for `--*_out` options and will eventually find `--ts_out` and then will look up to the `PATH` variable to find a command that matches the pattern `protoc-gen-*` which is in this case `protoc-gen-ts`.
What happens here is that you implicitly have requested the outputs from the `protoc-gen-ts` plugin.


Second: I'm don't think that you need to run which command if you don't have duplicate commands which is not possible in `unix` like systems.

**Comment by thesayyn** [comment]
> > Hey @CMCDragonkai. in lock file we have `^3.8.3` and i think it ought to work with 4.x.x.
> > But we have something else to fix here. as far as i can see that you are trying to use this with other plugins. I guess you understood the plugin wrong. You don't need any other `JS` related plugins if you are using this plugin.
> > so instead of you way you should use it like this;
> > `protoc --proto_path=proto/schemas --ts_out="proto/ts" ./proto/schemas/*.proto`
> > it will generate everything to the 'proto/ts' directory. you can import those files and they are ready to use.
> > keep in mind that in that directory theres `.ts` files instead of `.d.ts` files which means they contain all the necessary runtime code to run.
> > I would like assist you further if you can't get out of this situation.
> 
> I am now confused as well, using the command you suggested results in a generation of `.d.ts` files not `.ts` files:
> 
> ```
> AD+rcronin9@DESKTOP-GTR8EMA MINGW64 ~/Documents/github/js-polykey (polykey-app-bugs)
> $ ls ./src/proto/ts
> 
> AD+rcronin9@DESKTOP-GTR8EMA MINGW64 ~/Documents/github/js-polykey (polykey-app-bugs)
> $ protoc --proto_path=src/proto/schemas --ts_out="src/proto/ts" src/proto/schemas/Agent.proto 
> 
> AD+rcronin9@DESKTOP-GTR8EMA MINGW64 ~/Documents/github/js-polykey (polykey-app-bugs)
> $ ls ./src/proto/ts
> Agent_grpc_pb.d.ts  Agent_pb.d.ts
> ```

I suspect that you have already installed `improbable-eng/ts-protoc-gen` globally. If you did, you need to remove it first because when you are using this plugin, you don't need anything else. 

Can you share the output of `npm ls -g --depth=0` with me so that i can understand your problem better?

**Comment by CMCDragonkai** [comment]
I still get the same error:

```
[nix-shell:~/Projects/js-polykey]$ protoc \
$>   --proto_path=src/proto/schemas \
$>   --ts_out="src/proto/js" \
$>   ./src/proto/schemas/*.proto
/home/cmcdragonkai/Projects/js-polykey/node_modules/typescript/lib/typescript.js:12449
        return array.hasOwnProperty("pos") && array.hasOwnProperty("end");
                     ^

TypeError: Cannot read property 'hasOwnProperty' of null
    at Object.isNodeArray (/home/cmcdragonkai/Projects/js-polykey/node_modules/typescript/lib/typescript.js:12449:22)
    at createNodeArray (/home/cmcdragonkai/Projects/js-polykey/node_modules/typescript/lib/typescript.js:20812:25)
    at Object.createCallExpression (/home/cmcdragonkai/Projects/js-polykey/node_modules/typescript/lib/typescript.js:22099:95)
    at Object.createCall (/home/cmcdragonkai/Projects/js-polykey/node_modules/typescript/lib/typescript.js:3022:29)
    at createToObject (/home/cmcdragonkai/Projects/js-polykey/node_modules/protoc-gen-ts/index.js:49:14)
    at createMessage (/home/cmcdragonkai/Projects/js-polykey/node_modules/protoc-gen-ts/index.js:1016:5)
    at processMessageDescriptor (/home/cmcdragonkai/Projects/js-polykey/node_modules/protoc-gen-ts/index.js:1545:5)
    at processProtoDescriptor (/home/cmcdragonkai/Projects/js-polykey/node_modules/protoc-gen-ts/index.js:1590:12)
    at main (/home/cmcdragonkai/Projects/js-polykey/node_modules/protoc-gen-ts/index.js:1680:24)
    at Object.<anonymous> (/home/cmcdragonkai/Projects/js-polykey/node_modules/protoc-gen-ts/index.js:1765:1)
--ts_out: protoc-gen-ts: Plugin failed with status code 1.
```

Note that the `protoc` is coming from `grpc-tools` https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools

Are you assuming normal upstream `protoc`?

**Comment by CMCDragonkai** [comment]
Even if I use upstream `protoc`, the same error occurs.

**Comment by CMCDragonkai** [comment]
I don't have any other ts generator...

**Comment by thesayyn** [comment]
I will quickly take a look at this. 

Sorry i was out of work for a while.

**Comment by thesayyn** [comment]
We have landed a fix for this on master which will be available soon.

**Comment by paul-pop** [comment]
@thesayyn any chance you can trigger a 0.3.5 release with this fix?

**Comment by thesayyn** [comment]
Hey @paul-pop. I'll try to release it today.

**Comment by thesayyn** [comment]
Hey everyone, 0.3.5 has landed and must have fixed this problem already.

I was busy moving to another country.
