### ISSUE TITLE
Support for `optional` in proto3

### ISSUE THREAD

**Issue by sky-lake** [thesayyn/protoc-gen-ts#33]
Calling protoc with `--experimental_allow_proto3_optional` returns

> filename.proto is a proto3 file that contains optional fields, but code generator protoc-gen-ts hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.

For more information on implementation, see: https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md

**Comment by thesayyn** [comment]
This seems easy to implement. However we don't support oneof fields yet.

I'll land this feature as soon as we implement oneof fields. Any help is appreciated.

**Comment by thesayyn** [comment]
Update:

I have landed a PR #38 which will be followed by another PR to support oneof fields.

**Comment by thesayyn** [comment]
Hey. We have landed a new release candidate for this https://www.npmjs.com/package/protoc-gen-ts/v/0.3.6-rc2 

Let me know if it works for you 🤓

Also, please consider supporting me in any way you could.

**Comment by antiqe** [comment]
@thesayyn Thanks a lot strongly appreciate your work :)

**Comment by thesayyn** [comment]
I am so glad to hear that @antiqe
