### ISSUE TITLE
Repeated field problem in protobuf v2

### ISSUE THREAD

**Issue by ndunks** [thesayyn/protoc-gen-ts#41]
Based on the protobuf specification [here](https://developers.google.com/protocol-buffers/docs/proto3#simple)

Proto file that not have `syntax = "proto3";` on the first line will be treated as 'proto2' syntax.  And so if it has first line `syntax = "proto2";` its clean that its proto2 syntax. 

- [Proto2 repeated numeric](https://developers.google.com/protocol-buffers/docs/proto#specifying_field_rules)
- [Proto3 repeated numeric](https://developers.google.com/protocol-buffers/docs/proto3#specifying_field_rules)

In proto2 or proto3 the repeated field can be packed/not packed using special option:
``` proto
repeated int32 samples = 4 [packed=true];
repeated ProtoEnum results = 5 [packed=false];
```

There is a different between v2 an v3 on dealing with integer repeated field. on v2 there's no optimization or by default is `no packed integer`, its just an repeated field with same id.

I Found that this library ignoring that specification causing me to fail when rebuilt whatsapp protobuf that created using proto2 syntax.
I was try with specifyin [packed=false] but still no luck, so I need to manually patch the generated code because I have no time to make PR for this repo.

Note:
- If you compile proto using this library, and then decode and encode using same generated code, it will work and no error.
- Error happen when I decoding a binary message that came from other encoder (whatsapp server). It break on repeated field after I deeply investigate.

I know it error from generated ts code because I was using this before and no problems. Works fine using version before its breaking changes to simple getter/setter.

If you want, You can add a simple test (using nodejs assert is enough) to test against [this files](https://github.com/ndunks/whatsapp-protobuf/tree/master/test) or make binary message from other tools with same proto spec.

Thanks this library is great and I like the improvement to use direct getter/setter on field instead using a lot of get-set function.

**Comment by thesayyn** [comment]
Thank you for the report. I will add this to my backlog and get it fixed sooon.
