### ISSUE TITLE
Finish oneof support

### ISSUE THREAD

**Issue by melonmouse** [thesayyn/protoc-gen-ts#48]
Thanks so much for working on this project! Hope this bug will help :). I looked at your code for a bit to see if I could write you a pull request, but wasn't sure where to start.

To complete oneof support, there should be helper functions to determine what case is set.
https://developers.google.com/protocol-buffers/docs/reference/javascript-generated#oneof

So taking the example from above:
```
package account;
message Profile {
  oneof avatar {
    string image_url = 1;
    bytes image_data = 2;
  }
}
```

There should be a generated enum representing the cases, so for the above example:
```
proto.account.Profile.AvatarCase = {
  AVATAR_NOT_SET: 0,
  IMAGE_URL: 1,
  IMAGE_DATA: 2
};
```

And a getter that returns the enum value that is currently set, getAvatarCase().

**Comment by melonmouse** [comment]
P.S. if it is any help, if you'd write a "pseudo code" commit adding this functionality, I could complete that. Not sure if it would save you time, but wanted to offer :)

**Comment by thesayyn** [comment]
Hey, thank you for opening this. We had a brief conversation on another issue.

It makes more sense to continue the conversation here.



> P.S. if it is any help, if you'd write a "pseudo code" commit adding this functionality, I could complete that. Not sure if it would save you time, but wanted to offer :)

I can assist you on the way if you could open up a draft pull request.

**Comment by thesayyn** [comment]
Hey @melonmouse 

When you have some time, could you join the discussion at #39 about one-of-fields?
