### ISSUE TITLE
How do I bundle outputs for use in other typescript projects?

### ISSUE THREAD

**Issue by samlevin** [thesayyn/protoc-gen-ts#49]
Imagine a directory structure like:
```
protos \
  service1 
    blah.proto
    ...
   service2
     fubar.proto
```

assuming I generate working ts using this plugin, how can I export the output (while preserving directory strcuture) for the purpose of importing and using client stubs in other repositories?

**Comment by thesayyn** [comment]
I think you could accomplish this by giving protoc `protos` directory as the input and output directory at the same time.

then protoc would make generates files reside their respective protos.

**Comment by thesayyn** [comment]
Feel free to reopen if the solution that I described above does not solve your problem.
