### ISSUE TITLE
Help users understand tradeoffs with alternatives

### ISSUE THREAD

**Issue by alexeagle** [thesayyn/protoc-gen-ts#5]
It would be nice if the readme helped me understand whether to use this package or the alternative 
https://github.com/improbable-eng/ts-protoc-gen
with its Bazel rules
https://github.com/Dig-Doug/rules_typescript_proto

Do you already know what tradeoffs make this package better or that one for some use cases?

**Comment by thesayyn** [comment]
My inital intention was to make a protoc plugin that generates appropriate protocolbuffers classes which can be bundled with rollup. So when i had used other packages, I saw that they were missing something always. 

I have made some changes in the readme that explains these missing features;
https://github.com/thesayyn/protoc-gen-ts/commit/690f26e16cea9457aafbbb3d35e9aaa30550d648
