### ISSUE TITLE
disable namespace

### ISSUE THREAD

**Issue by mantou132** [thesayyn/protoc-gen-ts#50]
If the package name is a namespace name that ts does not support, then the generated ts cannot be used:

proto:

```
package xxx.xxx.xxx;
```

ts: 
```ts
export namespace xxx.xxx.xxx {}
```

**Comment by thesayyn** [comment]
Hey @mantou132 

Can you provide more details?

I am not sure that I follow.

**Comment by mantou132** [comment]
If the package name is a namespace name that Typescript does not support, then the generated ts cannot be used.

**Comment by thesayyn** [comment]
It would help me a lot to understand if you could give me a concrete example of the problem that you are facing.
because the example given above ought to work without any problems.

**Comment by thesayyn** [comment]
See the test case where I make sure that nested namespaces are working across versions

https://github.com/thesayyn/protoc-gen-ts/blob/e99f990f52f5e434da27ad219de56e7daae4657b/test/packagedirective.spec.ts#L16

**Comment by mantou132** [comment]
sorry, the method I used is incorrect, I close this issue
