### ISSUE TITLE
import error in generated ts files with namespace

### ISSUE THREAD

**Issue by alienzhangyw** [thesayyn/protoc-gen-ts#61]
When use the same package name in multiple .proto files, like
```
syntax = "proto3";

package Config;
```
In the generated ts file, there're import lines like
``` ts
import * as dependency_1 from "./ConfigA";
import * as dependency_2 from "./ConfigB";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace Config {
    ...enums and classes
}
```
Then we got errors like this:
![image](https://user-images.githubusercontent.com/58874541/123076754-00259c80-d44c-11eb-9688-1503cfb9bff0.png)
When using types and namespaces from dependency files, it should be `dependency_x.Config.XXX`.

PS: All serializeBinary() function in classes has typscript error, because return type may be undefined.
![image](https://user-images.githubusercontent.com/58874541/123077693-dd47b800-d44c-11eb-9b29-fea1624c115d.png)

**Comment by thesayyn** [comment]
Hey @alienzhangyw 

Thank you for the issue report. 

I will take a detailed look at it tomorrow.

**Comment by tomerzaidler** [comment]
Hey @thesayyn

**Comment by thesayyn** [comment]
I couldn't reproduce the issue. it would help me a lot if you could provide minimal proto files for reproduction.

**Comment by thesayyn** [comment]
> Hey @thesayyn
> Could we get an estimate on how much time it would take to fix it?

I can not provide any estimation but I will do my best to fix it as soon as I find an appropriate time.  

you are welcome to send a PR if you could find the problem

**Comment by alienzhangyw** [comment]
> I couldn't reproduce the issue. it would help me a lot if you could provide minimal proto files for reproduction.
> 
> also, the version of the plugin that you are using if you could.

Here's the minimal [repo](https://github.com/alienzhangyw/proto-gen-ts-demo).

**Comment by thesayyn** [comment]
thank you. I can confirm the issue arising from having the same package name for importing and imported files.

**Comment by thesayyn** [comment]
protoc-gen-ts@0.3.7 has been released. this should be fixed now. 

Feel free to reopen if the problem persists.

**Comment by alienzhangyw** [comment]
0 errors now, thanks!

**Comment by thesayyn** [comment]
Great!
