### ISSUE TITLE
Support of string-based enums

### ISSUE THREAD

**Issue by maZahaca** [thesayyn/protoc-gen-ts#71]
I know this kind of a limitation of `proto` protocol, but would be good to have the ability to have string-based enums in TS.

```
enum EmploymentStatus {
  unemployed = 0;
  employed = 1;
  student = 2;
  retired = 3;
}
```

it intended to be in the TS:
```
enum EmploymentStatus = {
  unemployed = 'unemployed';
  employed = 'employed';
  student = 'student';
  retired = 'retired';
}
```

**Comment by thesayyn** [comment]
This seems like a good idea but this would require the introduction of an option just for this plugin.  and that is something I would try to avoid. 

besides, I don't know how would this translate to wire format as we have to keep things interoperable with other languages.

**Comment by thesayyn** [comment]
also, using oneof fileds could be an option.

```proto
message EmploymentStatus {
  oneof name {
      bool unemployed = 0;
      bool employed = 1;
      bool student = 2;
      bool retired = 3;
  }
}


```typescript
const status = new EmploymentStatus({unemployed: true});
status.name // "unemployed" | "employed" | "student" | "retired"
```

**Comment by maZahaca** [comment]
Well here is an option if you initialize a server from proto file, which automatically transforms enums to strings correctly:

```
const exampleProto = `${__dirname}/../../../../../proto/example.proto`;

const options = {
  keepCase: true,
  longs: String,
  enums: String,
  defaults: true,
  oneofs: true,
};

const examplePackageDefinition = protoLoader.loadSync(exampleProto, options);

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const { examplepackage }: any = loadPackageDefinition(
  examplePackageDefinition,
);

const grpcServer = new Server();

grpcServer.addService(examplepackage.Example.service, {
  verifyMessage: serviceRequest<VerifyMessageInput, VerifyMessageResult>(
    verifyModel,
  ),
});
```

Basically when you pass an option `enums: String` while loading it transforms it to string.
Can we have something like this option for `protoc-gen-ts` ?

**Comment by thesayyn** [comment]
As far as I understand, you want to be able to get the name of an enum based on a value. At least that's what I got out of the enums option from proto-loader.

See: https://github.com/protobufjs/protobuf.js/blob/95b56817ef6fb9bdcb14d956c159da49d0889bff/tests/api_converters.js#L97
If you want to do the same, typescript has you covered. 

https://www.typescriptlang.org/docs/handbook/enums.html#reverse-mappings

Perhaps this could be an option for you?

**Comment by maZahaca** [comment]
Yes, this is it. The question was is it possible to have this conversion take place automatically? depends on some config as done for protoLoader options

**Comment by thesayyn** [comment]
I am not entirely sure that we can take the same approach as we do not compile protos on the runtime. they are compiled ahead of time thus we need a way to describe this behavior within the proto file. perhaps an option but we are against following any options that the upstream compiler does not provide.

I am open to any other suggestions apart from introducing a new option and force users to include the proto file that describes this option.

**Comment by thesayyn** [comment]
We won’t support this because neither it is in the spec nor could be useful for most users.

**Comment by tomasweigenast** [comment]
@thesayyn Here it says the ENUM specification: https://developers.google.com/protocol-buffers/docs/proto3#json
It must be a string, not an integer. If you use Protobuf with dart, it will serialize enums as strings, and this plugin will not understand that.
