### ISSUE TITLE
Support of google.rpc.status

### ISSUE THREAD

**Issue by maZahaca** [thesayyn/protoc-gen-ts#75]
Google's Status proto allows customizing errors thrown by the server and received by a client.
Here is one of the implementations I found out there, adopting this behavior into GRPC server/client:
https://github.com/quangtm210395/grpc-node-status-proto

Would it be possible to have the ability to customize errors as this?

**Comment by maZahaca** [comment]
As an example, I want to be able to call a custom function that will transform `standard` error to a custom one.

```
GetAccount(request: GetAccountRequest, metadata?: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<AccountResponse> {
            if (!metadata)
                metadata = new grpc_1.Metadata;
            if (!options)
                options = {};
            return new Promise((resolve, reject) => super.GetAccount(request, metadata, options, (error: grpc_1.ServiceError, response: AccountResponse) => {
                if (error) {
                    reject(error);
                }
                else {
                    resolve(response);
                }
            }));
        }
```

so, here would be useful to call customizable errorWrapper function e.g.: `reject(errorWrapper(error));`

**Comment by thesayyn** [comment]
The promise version of the RPC methods is a 1-1 match of the original RPCs (ones with callbacks). so I believe this should be handled in the user code, not in the generated code.

Additionally, it would create a third-party dependency on grpc-node-status if we implement this which is we can’t enforce on users.

**Comment by thesayyn** [comment]
We will rethink this when it might be useful for most users.
