### ISSUE TITLE
fromObject is not in v0.5.0

### ISSUE THREAD

**Issue by anant-singh** [thesayyn/protoc-gen-ts#90]
First I do want to thank you for creating this compiler. It is definitely very helpful and good features. I was especially excited on seeing the `fromObject` support but it seems to be that it's not in the current release. I can see the version that I installed is 0.5.0 but even in it's source I cannot find the changes related to fromObject.

**Comment by thesayyn** [comment]
Ah. I have cut the release with the wrong commit. I will release 0.6.0 today.

**Comment by thesayyn** [comment]
0.6.0 is now on npm.
