### ISSUE TITLE
Getting to 1.0

### ISSUE THREAD

**Issue by koblas** [thesayyn/protoc-gen-ts#93]
This is putting in a handful of notes.  I would like to help push this package to a formal 1.0 release so that it can get better adoption.  I'm selfish in that way which is I want to make sure I've got stable programs that I'm building against that have more maintainers...

There are a handful of things that I perceive that might help:

* <s>Moving the codebase to TypeScript</s> -- just makes it look better to outsiders
* <s>Issues: Windows</s>
* <s>Issues: CamelCase</s>
* <s>Issues: Namespaces</s>
* <s>`definition` in Unimplemented Service Definitions - it feels wrong to a first read</s>
* <s>Extra imports when not used</s>
* Escaping of reserved words (not gonna fix it.)
* <s>grpc-web client/support</s>

Anything else?

**Comment by thesayyn** [comment]
This is the exact list of this that I want to fix before the end of this year. Unfortunately, I don’t have that much free time as I used to have. 

- Issues: Windows -> this is something i am gonna pick up again really soon.
- Issues: CamelCase -> i will need help but i can’t accept a PR that sets this as the default behavior. it has to be controller via `ts_opt` flag. Also, snake_case is not that what we force on users. you get whatever you name your field so. this has never been my code style bias.  

- Issues: Namespaces -> same as CamelCase

- Extra imports when not used
- Escaping of reserved words: I will need help

- definition in Unimplemented Service Definitions - it feels wrong to a first read:  I am open to any other suggestions

**Comment by koblas** [comment]
I've got time I can pull out of a few project to help.

I'm going to start with moving to formal TypeScript since I've got a strong bias into making sure the system is helping me with types and I do find it annoying to have to keep comments in sync.  

There are some things that I think are breaking changes, it's probably good to target those at 1.0 since it's a major release and can justify breaking compatibility.

**Comment by cortopy** [comment]
> - grpc-web client/support

Which implementation would be the target? I personally use the improbable one because bundle size is much smaller than google's and supports binary for streams. So if I may, I'd like to vote for that one

**Comment by thesayyn** [comment]
> > * grpc-web client/support
> 
> Which implementation would be the target? I personally use the improbable one because bundle size is much smaller than google's and supports binary for streams. So if I may, I'd like to vote for that one

If both of them (google one, improbable one) have feature and public API parity, then we would like to support them both. . Personally, I don't like imposing choices on people.

**Comment by thesayyn** [comment]
Now that the windows issue is gone (and we test against windows as well), we can safely move on and add new features to the plugin. @koblas

**Comment by thesayyn** [comment]
#98 is here but it still needs a bit of work.

**Comment by thesayyn** [comment]
#132 has been merged.

**Comment by god-of-javascript** [comment]
Do you think about supporting returning native promises instead of having callback param?

**Comment by thesayyn** [comment]
All the items here are done. closing
