### ISSUE TITLE
deserialize of Array<number> gives Array<Array<number>>

### ISSUE THREAD

**Issue by jackpunt** [thesayyn/protoc-gen-ts#95]
Trying to catch up with the summer releases, using 0.3.9 at the moment.

My protobufs with Array<number> (from: repeated int32 zval=3) do not serialize/deserialize correctly.
(I have not yet check to see if the fail is on serialize or deserialize)

In particular: the deserialized object has the field/slot filled with Array[1][number]
Basically, an extra wrapping of Array<>

Has this been seen before? 
Is it corrected in a later release?

Look at the `indx` array below:

```
let msg3 = this.test_terImages(6);
let mbytes3 = msg3.serializeBinary(msg3)
let msg4 = gampb.AMessage.deserialize(mbytes3)
console.log(stime(), "msg3=", msg3.toObject(), "msg4=", msg4.toObject())  
```

<img width="1046" alt="Screen Shot 2021-10-22 at 3 42 16 PM" src="https://user-images.githubusercontent.com/455836/138530623-a82e7f2f-b5ed-416c-8a0e-b0d668b4c4ab.png">

**Comment by jackpunt** [comment]
Attempting to see if it is just a problem with .toObject()
So I re-serialized/deserialized and obtained: "Assertion Failed"
[so that seems to implicate a problem independent of .toObject()]

```
        let msg3: gampb.AMessage = this.test_terImages(6);
        let mbytes3 = msg3.serializeBinary()
        let msg4 = gampb.AMessage.deserialize(mbytes3)
        console.log(stime(), "msg3=", msg3.toObject(), "msg4=", msg4.toObject())
        let mbytes4 = msg4.serializeBinary()
        let msg5 = gampb.AMessage.deserialize(mbytes4)
        console.log(stime(), "msg3=", msg3.toObject(), "msg4=", msg4.toObject(), "msg5=", msg5.toObject())
```
<img width="1497" alt="Screen Shot 2021-10-22 at 4 24 04 PM" src="https://user-images.githubusercontent.com/455836/138532892-c5bb8854-c057-4f8e-a905-f9699186ad9a.png">

**Comment by thesayyn** [comment]
Oh, this is quite debugging work you have done over there. The issue seems to be arising from incorrectly generated packed fields. The solution is as simple as checking if the field is packed.

**Comment by thesayyn** [comment]
It has to be fixed here: https://github.com/thesayyn/protoc-gen-ts/blob/28a9276e3c2594dbed86bc27feb256953744af1a/src/field.js#L232
